export const F1_DRIVERS_2025 = [
  { code: 'VER', name: 'Max Verstappen', team: 'Red Bull Racing' },
  { code: 'LAW', name: 'Liam Lawson', team: 'Red Bull Racing' },
  { code: 'LEC', name: 'Charles Leclerc', team: 'Ferrari' },
  { code: 'HAM', name: 'Lewis Hamilton', team: 'Ferrari' },
  { code: 'NOR', name: 'Lando Norris', team: 'McLaren' },
  { code: 'PIA', name: 'Oscar Piastri', team: 'McLaren' },
  { code: 'RUS', name: 'George Russell', team: 'Mercedes' },
  { code: 'ANT', name: 'Kimi Antonelli', team: 'Mercedes' },
  { code: 'ALO', name: 'Fernando Alonso', team: 'Aston Martin' },
  { code: 'STR', name: 'Lance Stroll', team: 'Aston Martin' },
  { code: 'GAS', name: 'Pierre Gasly', team: 'Alpine' },
  { code: 'DOO', name: 'Jack Doohan', team: 'Alpine' },
  { code: 'ALB', name: 'Alexander Albon', team: 'Williams' },
  { code: 'SAI', name: 'Carlos Sainz', team: 'Williams' },
  { code: 'TSU', name: 'Yuki Tsunoda', team: 'Racing Bulls' },
  { code: 'HAD', name: 'Isack Hadjar', team: 'Racing Bulls' },
  { code: 'OCO', name: 'Esteban Ocon', team: 'Haas' },
  { code: 'BEA', name: 'Oliver Bearman', team: 'Haas' },
  { code: 'HUL', name: 'Nico Hulkenberg', team: 'Sauber' },
  { code: 'BOR', name: 'Gabriel Bortoleto', team: 'Sauber' },
];

export const F1_CONSTRUCTORS_2025 = [
  'Red Bull Racing',
  'Ferrari',
  'McLaren',
  'Mercedes',
  'Aston Martin',
  'Alpine',
  'Williams',
  'Racing Bulls',
  'Haas',
  'Sauber',
];
